      PROGRAM MAIN
      USE PHYPROJFISH
      USE USERFUNC
      IMPLICIT NONE
      INTEGER(KIND=4)::I,J,NOUT=1
      REAL(KIND=8)::TEND=1.0,T=0.0
      INTEGER(KIND=4)::CONTROL=0

      X_0=0.0,X_1=1.0,Y_0=0.0,Y_1=1.0
      M=60;N=60
      DX=(X_1-X_0)/M;DY=(Y_1-Y_0)/N
      CALL CYLINDER2DMESH
      WRITE(*,20)M,N,DX,DY
20    FORMAT('MESH GRID M*N',2I5,'DX DY','2F6.4')
      CALL INITIAL
      WRITE(*,60)'TIME=',T,'INITIAL DT=',DT
      DO WHILE(T.LE.TEND)
      CALL CFL
      T=T+DT
      WRITE(*,60)'TIME=',T,'CFL DT=',DT
      CALL PROJSOLA
      IF(T.GE.(0.005*NOUT))THEN
      CALL OUTPUT(NOUT)
      NOUT=NOUT+1
      ENDIF
      ENDDO
60    FORMAT(1X,A10,F10.5,1X,A10,F10.5)
61    FORMAT(1X,A10,F10.5,'WRITE FILE',1X,A10,I10)

      STOP
      END PROGRAM MAIN

